# Generated by Django 5.2.1 on 2025-05-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='last_attendance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
