# Generated by Django 5.2.1 on 2025-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_registereduser_last_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='last_attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
